### ISSUE TITLE
add ts-expect-error

### ISSUE THREAD

**Issue by rthomazel** [leandrotk/advanced-typescript#2]
we can use `@ts-expect-error` instead of comments like `// Error!`. The compiler will parse those.

**Comment by imteekay** [comment]
My intention was to make it explicit that there has a compiler error. With `@ts-expect-error` we lose this error, right? 🤔

**Comment by rthomazel** [comment]
Yes and no, I mean, the comment still shows an error there, but it doesn't stop compilation. And if there's no error, then using `expect-error` will result in an error haha

**Comment by imteekay** [comment]
Got it!
I added `@ts-expect-error` in [this PR](https://github.com/leandrotk/advanced-typescript/pull/11).
